### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Thomas-Gallant** [fingerprintjs/action-coverage-report-md#187]
I have recently implemented code coverage reports using this action, and I wanted to share where I think more documentation could be helpful. Thank you for making this GitHub Action!

I implemented this with Cypress and Istanbul js and React Native Web / Expo. 

## Update Usage section with example on how to publish to Job Summary section

Some people may not be aware of how to do this so documenting this would be nice. It is a cool feature to be able to use this action on pipeline runs that are not pull requests!

[More Info on Job Summaries](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary)
```yaml
      - uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage
        with:
          textReportPath: './coverage/coverage-final.txt'
          srcBasePath: ''
      
      - run: | 
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.coverage.outputs.markdownReport }}" >> $GITHUB_STEP_SUMMARY
```

![image](https://github.com/fingerprintjs/action-coverage-report-md/assets/60023923/6885b809-9e81-4060-905f-924f68f5e431)

## Update usage section with how to generate text reports with nyc package

For some reason I could not figure out a way to generate `.txt` reports. I used this command to generate the text report. 

```yaml
      - run: npx nyc report --reporter=text > coverage-final.txt
        working-directory: ./coverage
```

## Code links in report break if there are code files in the root folder of the repository

I do not know if this is a bug or not, but I needed to move my App.tsx file out of the root folder of my project. 
When I had App.tsx inside of my root folder, my reports generated as below: The links in the report redirected here:

https://github.com/SudoKuru/Frontend/blob/ed0aefe25c93ac6bf3425e417f8473558911ceeb/Frontend/App.tsx

The valid link should be:
https://github.com/SudoKuru/Frontend/blob/ed0aefe25c93ac6bf3425e417f8473558911ceeb/App.tsx

The link is incorrect because `Frontend` is the name of the repository and not a folder. When there is code in the root of the folder, it appears that the Istanbul reporter uses the repository name as the root folder. 

![image](https://github.com/fingerprintjs/action-coverage-report-md/assets/60023923/ef21593b-8a52-41ed-af6b-90aea2cc6c41)

This is the [PR](https://github.com/SudoKuru/Frontend/pull/233) for the project where I implemented Code Coverage using this action.
